// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dedzejfdokzryilzecag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZHplamZkb2t6cnlpbHplY2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzcwOTcsImV4cCI6MjA3NDQ1MzA5N30.FGl4s--SMHedlRszcM5O3XFLlfuQpmxqYj2HCDxleHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});